version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - my_network

  app:
    image: ems-app
    container_name: ems-app-container
    environment:
      APP_PORT: ${APP_PORT}
      DB_URL: ${DB_URL}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - postgres
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
